--select * from olapts.Credit_Committee_Lookup order by key_ 
drop table if exists olapts.Credit_Committee_Lookup;
CREATE TABLE olapts.Credit_Committee_Lookup(
    Key_ character varying ,
    Datamart_value character varying
);
 
INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ABC FACTORS-ΓΕΝΙΚΗ ΔΙΕΥΘΥΝΣΗ', N'1055')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ABC FACTORS-ΣΥΜΒΟΥΛΙΟ ΕΡΓΑΣΙΩΝ Ι', N'1052')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ABC FACTORS-ΣΥΜΒΟΥΛΙΟ ΕΡΓΑΣΙΩΝ ΙΙ', N'1053')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ABC FACTORS-ΤΜΗΜΑ ΑΞΙΟΛ ΚΙΝΔΥΝΟΥ ΟΦΕΙΛΕΤΩΝ', N'1054')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤ. W/SALE BANKING IV- ΥΠΟ Δ/ΝΤΩΝ ΚΕΝΤΡΟΥ', N'1159')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤ. W/SALE BANKING IV- ΥΠΟ ΥΠΟΔ/ΝΤΩΝ ΚΕΝΤΡΟΥ', N'1160')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤΕΡ. ΛΙΑΝ. ΤΡΑΠ - ΣΥΜΒΟΥΛΙΟ Ι', N'1166')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤΕΡ. ΛΙΑΝ. ΤΡΑΠ - ΣΥΜΒΟΥΛΙΟ ΙΙ', N'1167')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤΕΡ. ΛΙΑΝ. ΤΡΑΠ. ΙΙΙ - Senior Officer', N'1170')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤΕΡ. ΛΙΑΝ. ΤΡΑΠ. ΙΙΙ - ΥΠΟ ΤΟΝ Δ/ΝΤΗ', N'1168')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤΕΡ. ΛΙΑΝ. ΤΡΑΠ. ΙΙΙ - ΥΠΟ ΤΟΝ ΥΠΟΔ/ΝΤΗ', N'1169')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. W/SALE BANKING - ΣΥΜΒΟΥΛΙΟ Α', N'1154')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. W/SALE BANKING - ΣΥΜΒΟΥΛΙΟ Β', N'1155')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. W/SALE BANKING I', N'1150')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. W/SALE BANKING II', N'1151')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. W/SALE BANKING III', N'1152')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. W/SALE BANKING IV', N'1153')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤΟΔ. ΛΙΑΝ. ΤΡΑΠ. V', N'1165')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤΟΔ. ΛΙΑΝ. ΤΡΑΠ. Ι', N'1161')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤΟΔ. ΛΙΑΝ. ΤΡΑΠ. ΙV', N'1164')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤΟΔ. ΛΙΑΝ. ΤΡΑΠ. ΙΙ', N'1162')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤΟΔ. ΛΙΑΝ. ΤΡΑΠ. ΙΙΙ-(ΜΙΚΡ.ΕΠΙΧ)', N'1163')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΔΙΕΥΘΥΝΣΕΩΣ ΟΡΙΣΤΙΚΩΝ ΚΑΘΥΣΤΕΡΗΣΕΩΝ WHOLESALE BANKING - ΥΠΟ Δ/ΝΤΗ', N'1171')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΔΙΕΥΘΥΝΣΕΩΣ ΟΡΙΣΤΙΚΩΝ ΚΑΘΥΣΤΕΡΗΣΕΩΝ WHOLESALE BANKING - ΥΠΟ ΥΠΟΔ/ΝΤΗ', N'1172')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ABC FACTORS', N'1151')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ PRIVATE BANKING I', N'1180')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ PRIVATE BANKING II', N'1181')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'CEPAL', N'1182')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤ. W/SALE BANKING I', N'1156')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤ. W/SALE BANKING II', N'1157')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘΥΣΤ. W/SALE BANKING III', N'1158')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤΟΔ. ΛΙΑΝ. ΤΡΑΠ. ΙΙΙ', N'1163')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ARREARS COMMITTEE ALPHA BANK LUXEMBURG BRANCH', N'1178')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'CREDIT COMMITTEE ALPHA BANK LUXEMBURG BRANCH', N'1177')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'CREDIT COMMITTEE INTRAGROUP LOANS', N'1179')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΕΠΙΤΡΟΠΗ ΑΞΙΟΛΟΓΗΣΗΣ ΠΙΣΤΟΥΧΩΝ WHOLESALE BANKING ΜΕ ΑΔΥΝΑΜΙΑ ΠΛΗΡΩΜΗΣ', N'1173')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΔΙΟΙΚΗΣΕΩΣ', N'1011')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΔΙΕΥΘΥΝΣΕΩΣ FACTORING', N'1045')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΚΑΘΥΣΤΕΡΗΣΕΩΝ ΔΙΟΙΚΗΣΕΩΣ', N'1061')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙO ΚΑΘΥΣΤΕΡΗΣΕΩΝ ΓΕΝΙΚΩΝ ΔΙΕΥΘΥΝΤΩΝ', N'1071')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΑΝΩΤΕΡΟ ΣΥΜΒΟΥΛΙΟ ΚΑΘΥΣΤΕΡΗΣΕΩΝ', N'1081')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΚΑΘ. Μ.ΔΙΑΧ. ΠΙΣΤ. Ε.Χ.&ΚΑΘ. ΜΕΓ.&ΜΕΣ. ΕΠIX.', N'1082')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΑΡ. ΠΕΛ. W/SALE BANKING ΜΕ ΛΗΞ/ΜΕΣ ΟΦΕΙΛΕΣ', N'1026')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. ΕΠΙΧ/ΩΝ - ΣΥΜΒ. ΥΠΟ ΤΟΝ Δ/ΝΤΗ ICD', N'1091')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΠΙΣΤ. ΕΠΙΧ/ΩΝ - ΣΥΜΒ. ΥΠΟ ΤΟΝ ΥΠΟ/ΝΤΗ ICD', N'1092')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ.ΠΙΣΤ.ΜΙΚ.ΕΠΙΧ.& ΦΟΡΕΩΝ-ΥΠΟ ΤΟΥΣ ΥΠ/ΝΤΕΣ ΤΗΣ ΔΛΠ', N'1142')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ.ΠΙΣΤ.ΜΙΚ.ΕΠΙΧ.& ΦΟΡΕΩΝ-ΥΠΟ ΤΟΥΣ SENIOR CREDIT OFFICERS', N'1143')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΔΛΠ-ΣΥΜΒΟΥΛΙΟ ΡΥΘΜΙΣΕΩΝ ΔΙΟΙΚΗΣΕΩΣ', N'1144')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΔΛΠ-ΣΥΜΒΟΥΛΙΟ ΡΥΘΜΙΣΕΩΝ ΓΕΝ. Δ/ΝΤΩΝ', N'1145')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΡΥΘΜ. ΥΠΟ ΤΟΥΣ Δ/ΝΤΕΣ ΔΛΠ ΚΑΙ Δ.Α.Ε.Χ.Λ.Τ', N'1146')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΡΥΘΜ. ΜΗ ΚΑΤΑΓΓ/ΝΩΝ ΟΦΕΙΛΩΝ ΜΙΚ.ΕΠΙΧ & ΦΟΡΕΩΝ –ΥΠΟ Δ/ΝΤΗ ΤΗΣ Δ.Λ.Π.', N'1147')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΡΥΘΜ. ΜΗ ΚΑΤΑΓΓ/ΝΩΝ ΟΦΕΙΛΩΝ ΜΙΚ.ΕΠΙΧ & ΦΟΡΕΩΝ –ΥΠΟ ΥΠΟΔ. ΤΗΣ Δ.Λ.Π.', N'1148')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ. ΡΥΘΜ. ΜΗ ΚΑΤΑΓΓ/ΝΩΝ ΟΦΕΙΛΩΝ ΜΙΚ.ΕΠΙΧ & ΦΟΡΕΩΝ –ΥΠΟ S.C.O. ΤΗΣ Δ.Λ.Π', N'1149')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒ.ΠΙΣΤ.ΜΙΚ.ΕΠΙΧ.& ΦΟΡΕΩΝ-ΥΠΟ ΤΟΝ Δ/ΝΤΗ ΤΗΣ ΔΛΠ', N'1141')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΔΙΕΥΘΥΝΣΕΩΣ ΥΠΟΣΤΗΡΙΞΕΩΣ ΚΑΘΥΣΤΕΡΗΣΕΩΝ WHOLESALE BANKING-ΥΠΟ Δ/ΝΤΗ', N'1174')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΤΟΜΕΑ WHOLESALE BANKING - ΥΠΟΔΙΕΥΘΥΝΤΩΝ ΔΙΕΥΘΥΝΣΕΩΝ', N'1023')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΜΟΝΑΔΟΣ ΠΕΛΑΤΕΙΑΚΗΣ ΚΑΛΥΨΕΩΣ', N'1042')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΔΙΕΥΘΥΝΣΕΩΣ ΔΙΚΤΥΟΥ ΕΠΙΧΕΙΡΗΜΑΤΙΚΩΝ ΚΕΝΤΡΩΝ', N'1043')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΔΤΜΕ - ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΔΙΕΥΘΥΝΤΩΝ ΔΙΕΥΘΥΝΣΕΩΝ', N'1111')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΔΤΜΕ - ΣΥΜΒΟΥΛΙΟ ΠΙΣΤΟΔΟΤΗΣΕΩΝ ΥΠΟΔΙΕΥΘΥΝΤΩΝ ΔΙΕΥΘΥΝΣΕΩΝ', N'1112')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ABC FACTORS-ΣΥΜΒΟΥΛΙΟ ΕΡΓΑΣΙΩΝ', N'1183')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΑΒC FACTORS-ΣΥΜΒΟΥΛΙΟ ΕΡΓΑΣΙΩΝ ABC FACTORS', N'1184')
;INSERT INTO olapts.Credit_Committee_Lookup (Key_, Datamart_value) VALUES (N'ΣΥΜΒΟΥΛΙΟ ΠΕΡΙΦΕΡΕΙΑΣ ΔΙΕΥΘΥΝΣΕΩΣ ΔΙΚΤΥΟΥ ΕΠΙΧΕΙΡΗΜΑΤΙΚΩΝ ΚΕΝΤΡΩΝ', N'1044')